export enum ErrorCodes {
  FILE_SIZE_EXCEEDED,
  DUPLICATE_EMAIL,
  PHONE_EXISTS,
  EMAIL_EXISTS,
  ENTITY_NOT_FOUND,
  ENTITY_ALREADY_FOUND,
  FILE_REQUIRED,
  FILE_TYPE_NOT_ALLOWED,
  TITLE_EXISTS,
  ENTITY_ALREADY_EXISTS,
}
